# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
 
N = 3
Name="app"
IP="192.168.77."
RAM=500 #megabytes
Vagrant.configure("2") do |config|
    (1..N).each do |machine_id|
		config.vm.define Name+"#{machine_id}" do |node|
			node.vm.box = "hashicorp/precise64"
			node.vm.usable_port_range = (2200..2250)
			node.vm.hostname = Name+"#{machine_id}"
			node.vm.network "private_network", ip: IP+"#{20+machine_id}", virtualbox__intnet: "intnet"
			node.ssh.password = "vagrant"
			node.vm.provider "virtualbox" do |vb|
				vb.customize ["modifyvm", :id, "--memory", RAM]
				vb.name = Name+"#{machine_id}" 
			end
		end
	end
end


